name: malawi
description: Google Sheets and SFTP Excel to DHIS2 HIV Indicators Pipeline
collections: null
workflows:
  HIV-Indicators-GoogleSheets-to-DHIS2-Workflow:
    name: HIV Indicators Google Sheets to DHIS2 Workflow
    jobs:
      Get-GoogleSheets-Data:
        name: Get Google Sheets Data
        adaptor: '@openfn/language-googlesheets@3.0.13'
        credential: null
        body:
          path: ./jobs/get-googlesheets-data.js
      Get-SFTP-Data:
        name: Get SFTP Excel Data
        adaptor: '@openfn/language-sftp@1.0.0'
        credential: null
        body:
          path: ./jobs/get-sftp-data.js
      Process-Excel-Data:
        name: Process Excel Data
        adaptor: '@openfn/language-common@2.4.0'
        credential: null
        body:
          path: ./jobs/process-excel-data.js
      Generate-DHIS2-Payload:
        name: Generate DHIS2 Payload
        adaptor: '@openfn/language-common@2.4.0'
        credential: null
        body:
          path: ./jobs/generate-dhis2-payload.js
      Upload-To-DHIS2:
        name: Upload to DHIS2
        adaptor: '@openfn/language-dhis2@6.3.4'
        credential: null
        body:
          path: ./jobs/upload-to-dhis2.js
          
    triggers:
      webhook:
        type: webhook
        enabled: true
      sftp-webhook:
        type: webhook
        enabled: true
    edges:
      webhook->Get-GoogleSheets-Data:
        source_trigger: webhook
        target_job: Get-GoogleSheets-Data
        condition_type: always
        enabled: true
      sftp-webhook->Get-SFTP-Data:
        source_trigger: sftp-webhook
        target_job: Get-SFTP-Data
        condition_type: always
        enabled: true
      Get-GoogleSheets-Data->Generate-DHIS2-Payload:
        source_job: Get-GoogleSheets-Data
        target_job: Generate-DHIS2-Payload
        condition_type: on_job_success
        enabled: true
      Get-SFTP-Data->Process-Excel-Data:
        source_job: Get-SFTP-Data
        target_job: Process-Excel-Data
        condition_type: on_job_success
        enabled: true
      Process-Excel-Data->Generate-DHIS2-Payload:
        source_job: Process-Excel-Data
        target_job: Generate-DHIS2-Payload
        condition_type: on_job_success
        enabled: true
      Generate-DHIS2-Payload->Upload-To-DHIS2:
        source_job: Generate-DHIS2-Payload
        target_job: Upload-To-DHIS2
        condition_type: on_job_success
        enabled: true