services:
  sftp_data_config:
    image: alpine:latest
    command: sh -c "
      echo 'Starting SFTP data importer...' &&
      mkdir -p /sftp-data/excel-files &&
      echo 'Created excel-files directory' &&
      cp /data-imports/*.xlsx /sftp-data/excel-files/ &&
      echo 'Copied Excel files:' &&
      ls -la /sftp-data/excel-files/ &&
      echo 'SFTP data import completed successfully'"
    configs:
      - source: dhis2_hiv_indicators_xlsx
        target: /data-imports/DHIS2_HIV_Indicators.xlsx
      - source: direct_queries_xlsx
        target: /data-imports/Direct_Queries_Q1_2025_MoH_Reports.xlsx
      - source: q2fy25_dq_sites_xlsx
        target: /data-imports/Q2FY25_DQ_253_sites.xlsx
    volumes:
      - sftp-data:/sftp-data
    networks:
      - sftp
    deploy:
      replicas: 1
      restart_policy:
        condition: none

volumes:
  sftp-data:
    external: true

networks:
  sftp:
    name: sftp-storage_sftp
    external: true

configs:
  dhis2_hiv_indicators_xlsx:
    file: ./data/DHIS2_HIV Indicators.xlsx
    name: dhis2_hiv_indicators_xlsx-${dhis2_hiv_indicators_xlsx_DIGEST:?err}
    labels:
      name: sftp_data
  direct_queries_xlsx:
    file: ./data/Direct Queries - Q1 2025 MoH Reports.xlsx
    name: direct_queries_xlsx-${direct_queries_xlsx_DIGEST:?err}
    labels:
      name: sftp_data
  q2fy25_dq_sites_xlsx:
    file: ./data/Q2FY25_DQ_253_sites.xlsx
    name: q2fy25_dq_sites_xlsx-${q2fy25_dq_sites_xlsx_DIGEST:?err}
    labels:
      name: sftp_data
