services:
  openfn_workflow_manager:
    image: ${OPENFN_WORKFLOWS_IMAGE:-openfn-workflows:latest}
    networks:
      - postgres
      - sftp
    environment:
      OPENFN_ENDPOINT: ${OPENFN_ENDPOINT:-http://openfn:4000}
      OPENFN_API_KEY: ${OPENFN_API_KEY:-}
      OPENFN_ADMIN_USER: ${OPENFN_ADMIN_USER:-}
      OPENFN_ADMIN_PASSWORD: ${OPENFN_ADMIN_PASSWORD:-}
      WORKFLOW_NAME: ${OPENFN_WORKFLOW_NAME:-sftp-dhis2}
      MODE: deploy
      PACKAGE_LIFECYCLE: "true"
      DRY_RUN: ${OPENFN_WORKFLOW_DRY_RUN:-false}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      labels:
        - "openfn.workflow.manager=true"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  postgres:
    name: postgres_public
    external: true
  sftp:
    name: sftp-storage_sftp
    external: true
