services:
  openfn_workflow_manager:
    image: ${OPENFN_WORKFLOWS_IMAGE:-openfn-workflows:local}
    networks:
      - postgres
    environment:
      OPENFN_ENDPOINT: ${OPENFN_ENDPOINT:-http://openfn:4000}
      OPENFN_API_KEY: ${OPENFN_API_KEY:-}
      OPENFN_ADMIN_USER: ${OPENFN_ADMIN_USER:-}
      OPENFN_ADMIN_PASSWORD: ${OPENFN_ADMIN_PASSWORD:-}
      WORKFLOW_NAME: ${OPENFN_WORKFLOW_NAME:-sftp-dhis2}
      MODE: deploy
      PACKAGE_LIFECYCLE: "true"
      DRY_RUN: ${OPENFN_WORKFLOW_DRY_RUN:-false}
      # SFTP Configuration
      SFTP_HOST: ${SFTP_HOST:-sftp-server}
      SFTP_PORT: ${SFTP_PORT:-22}
      SFTP_USER: ${SFTP_USER:-openfn}
      SFTP_PASSWORD: ${SFTP_PASSWORD:-instant101}
      # DHIS2 Configuration
      DHIS2_ENDPOINT: ${DHIS2_ENDPOINT:-}
      DHIS2_USERNAME: ${DHIS2_USERNAME:-}
      DHIS2_PASSWORD: ${DHIS2_PASSWORD:-}
      # General Configuration
      LOG_LEVEL: ${OPENFN_LOG_LEVEL:-info}
      MAX_RETRIES: ${OPENFN_MAX_RETRIES:-3}

networks:
  postgres:
    name: postgres_public
    external: true
  openfn_public:
    name: openfn_public
    external: true