#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKFLOWS_DIR="$SCRIPT_DIR/workflows"

IMAGE_NAME="${1:-openfn-workflows:local}"
MODE_ENV="${MODE:-deploy}"
WORKFLOW_NAME_ENV="${WORKFLOW_NAME:-}"
OPENFN_ENDPOINT_ENV="${OPENFN_ENDPOINT:-http://172.17.0.1:4000}"
OPENFN_API_KEY_ENV="${OPENFN_API_KEY:-apiKey}"
OPENFN_ADMIN_USER_ENV="${OPENFN_ADMIN_USER:-root@openhim.org}"
OPENFN_ADMIN_PASSWORD_ENV="${OPENFN_ADMIN_PASSWORD:-instant101secure}"
SFTP_USER_ENV="${SFTP_TEST_USER:-openfn}"
SFTP_PASSWORD_ENV="${SFTP_TEST_PASSWORD:-instant101}"

echo "Running $IMAGE_NAME against $OPENFN_ENDPOINT_ENV..."

docker run --rm \
  -v "${WORKFLOWS_DIR}:/app/workflows" \
  -e MODE="$MODE_ENV" \
  -e WORKFLOW_NAME="$WORKFLOW_NAME_ENV" \
  -e WORKFLOW_PATH=/app/workflows \
  -e OPENFN_ENDPOINT="$OPENFN_ENDPOINT_ENV" \
  -e OPENFN_API_KEY="$OPENFN_API_KEY_ENV" \
  -e OPENFN_ADMIN_USER="$OPENFN_ADMIN_USER_ENV" \
  -e OPENFN_ADMIN_PASSWORD="$OPENFN_ADMIN_PASSWORD_ENV" \
  -e SFTP_TEST_USER="$SFTP_USER_ENV" \
  -e SFTP_TEST_PASSWORD="$SFTP_PASSWORD_ENV" \
  "$IMAGE_NAME"

