version: "3.9"

services:
  dhis2-db-init:
    image: ${POSTGRES_IMAGE}
    environment:
      POSTGRES_HOST: ${DHIS2_DATABASE_HOST}
      POSTGRES_PORT: ${DHIS2_DATABASE_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DHIS2_DATABASE_NAME: ${DHIS2_DATABASE_NAME}
      DHIS2_DATABASE_USERNAME: ${DHIS2_DATABASE_USERNAME}
      DHIS2_DATABASE_PASSWORD: ${DHIS2_DATABASE_PASSWORD}
    configs:
      - source: dhis2-db-init.sh
        target: /docker-entrypoint-initdb.d/dhis2-db-init.sh
        mode: 0755
    command: >
      bash -c "
        echo 'Starting DHIS2 database initialization...'
        
        # Wait for PostgreSQL to be ready
        until pg_isready -h $${POSTGRES_HOST} -p $${POSTGRES_PORT} -U $${POSTGRES_USER}; do
          echo 'Waiting for PostgreSQL server to be ready...'
          sleep 2
        done
        
        echo 'PostgreSQL is ready. Running DHIS2 database initialization...'
        /docker-entrypoint-initdb.d/dhis2-db-init.sh
        
        echo 'DHIS2 database initialization completed successfully'
      "
    networks:
      - postgres
    deploy:
      replicas: 1
      restart_policy:
        condition: none
      labels:
        - name=dhis2-db-init

configs:
  dhis2-db-init.sh:
    name: dhis2_db_init_sh-${dhis2_db_init_sh_DIGEST:?err}
    file: ./dhis2-db-init.sh
    labels:
      name: dhis2-db-init

networks:
  postgres:
    name: postgres_public
    external: true
